// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eco_farma_API;

#nullable disable

namespace eco_farma_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eco_farma_API.Classes.Avaliacao", b =>
                {
                    b.Property<int>("id_avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_avaliacao"));

                    b.Property<string>("autor")
                        .HasColumnType("text");

                    b.Property<string>("avaliacao")
                        .HasColumnType("text");

                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<double>("nota")
                        .HasColumnType("double precision");

                    b.HasKey("id_avaliacao");

                    b.ToTable("avaliacao", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Avaliacao_produto", b =>
                {
                    b.Property<int>("id_avaliacao_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_avaliacao_produto"));

                    b.Property<string>("autor")
                        .HasColumnType("text");

                    b.Property<string>("avaliacao")
                        .HasColumnType("text");

                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<int>("id_produto")
                        .HasColumnType("integer");

                    b.Property<double>("nota")
                        .HasColumnType("double precision");

                    b.HasKey("id_avaliacao_produto");

                    b.ToTable("avaliacao_produto", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_cliente"));

                    b.Property<string>("cep")
                        .HasColumnType("text");

                    b.Property<string>("cpf")
                        .HasColumnType("text");

                    b.Property<string>("data_nasc")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("endereco")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<int>("numero")
                        .HasColumnType("integer");

                    b.Property<string>("senha")
                        .HasColumnType("text");

                    b.Property<string>("sexo")
                        .HasColumnType("text");

                    b.Property<string>("telefone")
                        .HasColumnType("text");

                    b.HasKey("id_cliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Cupom", b =>
                {
                    b.Property<int>("id_cupom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_cupom"));

                    b.Property<string>("codigo")
                        .HasColumnType("text");

                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.HasKey("id_cupom");

                    b.ToTable("cupom", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Entrega", b =>
                {
                    b.Property<int>("id_entrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_entrega"));

                    b.Property<int>("id_entregador")
                        .HasColumnType("integer");

                    b.Property<int>("id_pedido")
                        .HasColumnType("integer");

                    b.HasKey("id_entrega");

                    b.ToTable("entrega", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Entregador", b =>
                {
                    b.Property<int>("id_entregador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_entregador"));

                    b.Property<string>("cep")
                        .HasColumnType("text");

                    b.Property<string>("cpf")
                        .HasColumnType("text");

                    b.Property<string>("data_nasc")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("endereco")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<int>("numero")
                        .HasColumnType("integer");

                    b.Property<string>("senha")
                        .HasColumnType("text");

                    b.Property<string>("sexo")
                        .HasColumnType("text");

                    b.Property<string>("telefone")
                        .HasColumnType("text");

                    b.HasKey("id_entregador");

                    b.ToTable("entregador", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Farmacia", b =>
                {
                    b.Property<int>("id_farmacia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_farmacia"));

                    b.Property<string>("cep")
                        .HasColumnType("text");

                    b.Property<string>("cnpj")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("endereco")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<int>("numero")
                        .HasColumnType("integer");

                    b.Property<string>("senha")
                        .HasColumnType("text");

                    b.Property<string>("telefone")
                        .HasColumnType("text");

                    b.HasKey("id_farmacia");

                    b.ToTable("farmacia", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Pedido", b =>
                {
                    b.Property<int>("id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_pedido"));

                    b.Property<int>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<int>("id_farmacia")
                        .HasColumnType("integer");

                    b.Property<int>("id_produto")
                        .HasColumnType("integer");

                    b.Property<double>("preco_produto")
                        .HasColumnType("double precision");

                    b.Property<int>("qtd_produto")
                        .HasColumnType("integer");

                    b.HasKey("id_pedido");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Produto", b =>
                {
                    b.Property<int>("id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_produto"));

                    b.Property<byte[]>("anexo")
                        .HasColumnType("bytea");

                    b.Property<string>("categoria")
                        .HasColumnType("text");

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.Property<int>("estoque")
                        .HasColumnType("integer");

                    b.Property<int>("id_farmacia")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<double>("preco")
                        .HasColumnType("double precision");

                    b.HasKey("id_produto");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Promocao", b =>
                {
                    b.Property<int>("id_promocao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_promocao"));

                    b.Property<int>("id_produto")
                        .HasColumnType("integer");

                    b.Property<double>("preco_promocao")
                        .HasColumnType("double precision");

                    b.HasKey("id_promocao");

                    b.ToTable("promocao", (string)null);
                });

            modelBuilder.Entity("eco_farma_API.Classes.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_papel")
                        .HasColumnType("integer");

                    b.Property<string>("papel")
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.ToTable("usuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
